views:
  - title: Main
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.outside_humidity
      - type: custom:mini-graph-card
        entities:
          - sensor.outside_temperature
        show:
          extrema: true
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.outside_temperature
        show:
          extrema: true
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 60
        entities:
          - entity: sensor.random0_100
            name: Random 0 - 100
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 20
        lower_bound: 0
        upper_bound: 100
        # agregate_fun: median
        entities:
          - entity: sensor.random0_100
            name: Random MEDIAN
            aggregate_func: median
          - entity: sensor.random0_100
            name: Random AVG
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 120
        lower_bound: 0
        upper_bound: 1000
        logarithmic: true
        smoothing: false
        height: 400
        show:
          points: true
        entities:
          - entity: sensor.random_0_1000
            name: log(150 - 1000) Gradients
            aggregate_func: last
        color_thresholds:
          - value: 0
            color: "#00ff00"
          - value: 200
            color: "#ffff00"
          - value: 350
            color: "#ff9900"
          - value: 600
            color: "#ff0000"
      - type: custom:mini-graph-card
        hours_to_show: 1
        points_per_hour: 120
        lower_bound: 0
        upper_bound: 1000
        # logarithmic: true
        smoothing: false
        height: 600
        show:
          extrema: true
        #   points: true
        entities:
          - entity: sensor.random_0_1000
            name: log(150 - 1000) Simple
            aggregate_func: last
        color_thresholds:
          - value: 0
            color: green
          - value: 200
            color: red
          - value: 1000
            color: blue
      - type: custom:mini-graph-card
        entities:
          - sensor.non_existant
          - sensor.random_0_1000
          - sensor.non_existant_2
